-- NEUTRALIZED 2026-06-19 (release-readiness audit).
--
-- This migration originally TRUNCATEd every user table and ran
-- `DELETE FROM auth.users` — a one-shot factory reset. The old header claimed it
-- was "safe to leave in /migrations" because it's a no-op on an empty DB. That is
-- wrong: on any fresh environment (staging, a new prod, or a restored backup)
-- `supabase db push` replays it and erases all users + data.
--
-- It is already recorded as applied on the current production DB, so emptying its
-- body has no effect there (db push never re-runs an applied migration). Reduced
-- to a no-op so it can never wipe a fresh/restored database.
--
-- A real factory reset is now an out-of-band admin script, not an auto-migration.
SELECT 1;
